#!/bin/sh

if [ "$#" != 1 ]
then
  echo "Usage: trimspace <file pattern matcher>"
else
  find . -type f -name "$1" -exec sh -c 'for i;do sed 's/[[:space:]]*$//' "$i">/tmp/.$$ && mv /tmp/.$$ "$i";done' arg0 {} +
fi


